/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.udptokenclienteservidor;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import javax.swing.JOptionPane;


    
public class ClienteGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteGUI.class.getName());

    private DatagramSocket socketCliente;
    private boolean escutando = false;
    
    public ClienteGUI() {
        initComponents();
    }
    
   private String enviarRequisicaoSimples(String comando) {
        try (DatagramSocket socketTemp = new DatagramSocket()) {
            socketTemp.setSoTimeout(3000);
            DatagramPacket pacoteEnvio = ComunicadorUDP.montaMensagem(comando, "localhost", 1234);
            ComunicadorUDP.enviaMensagem(socketTemp, pacoteEnvio);
            DatagramPacket pacoteResposta = ComunicadorUDP.recebeMensagem(socketTemp);
            if (pacoteResposta != null) return new String(pacoteResposta.getData()).trim();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null; 
    }
   
   private void iniciarConexao() {
        try {
            socketCliente = new DatagramSocket();
            escutando = true;
            
            // escutando o servidor
            Thread ouvinte = new Thread(() -> {
                while (escutando) {
                    DatagramPacket pacote = ComunicadorUDP.recebeMensagem(socketCliente);
                    if (pacote != null) {
                        String mensagemRecebida = new String(pacote.getData()).trim();
                        processarMensagemDoServidor(mensagemRecebida);
                    }
                }
            });
            ouvinte.setDaemon(true);
            ouvinte.start();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "erro ao abrir porta UDP no cliente.");
        }
    }
   
    private void processarMensagemDoServidor(String mensagem) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            String[] partes = mensagem.split(";");
            
            if (partes[0].equals("OK_LOGIN")) {
                lblResultadoToken.setText("aguardando tokens...");
                JOptionPane.showMessageDialog(this, partes[1]);
            } else if (partes[0].equals("ERRO")) {
                JOptionPane.showMessageDialog(this, partes[1], "Erro", JOptionPane.ERROR_MESSAGE);
            } else if (partes[0].equals("NOVO_TOKEN")) {
                lblResultadoToken.setText("Token Atual: " + partes[1]);
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblResultadoToken = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtEmailBusca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLogar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cliente UDP");

        jLabel2.setText("Cadastro do Usuário");

        jLabel3.setText("Nome:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Pedir Token");

        lblResultadoToken.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResultadoToken.setText("Token: N/A");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        txtEmailBusca.addActionListener(this::txtEmailBuscaActionPerformed);

        jLabel4.setText("Email:");

        btnLogar.setText("Logar");
        btnLogar.addActionListener(this::btnLogarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(btnLogar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblResultadoToken)
                                            .addComponent(txtEmailBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogar)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoToken)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "preencha o nome");
            return;
        }

        String resposta = enviarRequisicaoSimples("CADASTRO;" + nome);
        
        if (resposta != null) {
            String[] partes = resposta.split(";");
            if (partes[0].equals("OK_CADASTRO")) {
                JOptionPane.showMessageDialog(this, "conta criada. \nEmail: " + partes[1]);
                txtEmailBusca.setText(partes[1]); 
                txtNome.setText("");
            } else {
                JOptionPane.showMessageDialog(this, partes[1], "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "erro de rede no cadastro.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtEmailBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailBuscaActionPerformed
        
    }//GEN-LAST:event_txtEmailBuscaActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
       String email = txtEmailBusca.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o email para logar");
            return;
        }
        
        if (socketCliente == null || socketCliente.isClosed()) {
            iniciarConexao();
        }

        String comando = "LOGIN;" + email;
        DatagramPacket pacoteEnvio = ComunicadorUDP.montaMensagem(comando, "localhost", 1234);
        ComunicadorUDP.enviaMensagem(socketCliente, pacoteEnvio);
    }//GEN-LAST:event_btnLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblResultadoToken;
    private javax.swing.JTextField txtEmailBusca;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
