/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.udptokenclienteservidor;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import javax.swing.JOptionPane;

/**
 *
 * @author edusmrs
 */
public class ClienteGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteGUI.class.getName());

    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI() {
        initComponents();
    }
    
    private String enviarRequisicaoUDP(String comando) {
        try (DatagramSocket socketCliente = new DatagramSocket()) {
            socketCliente.setSoTimeout(3000); // 3 segundos de timeout
            
            DatagramPacket pacoteEnvio = ComunicadorUDP.montaMensagem(comando, "localhost", 1234);
            ComunicadorUDP.enviaMensagem(socketCliente, pacoteEnvio);
            
            DatagramPacket pacoteResposta = ComunicadorUDP.recebeMensagem(socketCliente);
            if (pacoteResposta != null) {
                return new String(pacoteResposta.getData()).trim();
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Erro na comunicação UDP", ex);
        }
        return null; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPedirToken = new javax.swing.JButton();
        lblResultadoToken = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmailToken = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cliente UDP");

        jLabel2.setText("Cadastro do Usuário");

        jLabel3.setText("Nome:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Pedir Token");

        btnPedirToken.setText("Pedir Token");
        btnPedirToken.addActionListener(this::btnPedirTokenActionPerformed);

        lblResultadoToken.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResultadoToken.setText("Token: N/A");

        jLabel7.setText("Email:");

        txtEmailToken.addActionListener(this::txtEmailTokenActionPerformed);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmailToken, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblResultadoToken)
                                    .addComponent(btnPedirToken))
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnCadastrar)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnPedirToken)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoToken)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnPedirTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirTokenActionPerformed
       String email = txtEmailToken.getText().trim();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o email para buscar o token!");
            return;
        }
        
        String resposta = enviarRequisicaoUDP("SOLICITAR_TOKEN;" + email);
        if (resposta != null) {
            String[] partes = resposta.split(";");
            if (partes.length >= 2 && partes[0].equals("TOKEN")) {
                lblResultadoToken.setText("Token: " + partes[1]);
            } else {
                lblResultadoToken.setText("Token: Não encontrado");
                JOptionPane.showMessageDialog(this, partes.length >= 2 ? partes[1] : "Resposta inválida", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            lblResultadoToken.setText("Token: Falha na conexão");
            JOptionPane.showMessageDialog(this, "Erro de rede (Timeout).", "Erro UDP", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnPedirTokenActionPerformed

    private void txtEmailTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailTokenActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText().trim();
        
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o nome para gerar o cadastro!");
            return;
        }
        
        // Se o nome tiver espaços repetidos, o trim() cuida das pontas, mas é bom avisar
        if (!nome.contains(" ")) {
            int resposta = JOptionPane.showConfirmDialog(this, 
                "Você inseriu apenas um nome. O email ficará sem sobrenome. Deseja continuar?", 
                "Aviso", JOptionPane.YES_NO_OPTION);
            if (resposta != JOptionPane.YES_OPTION) return;
        }

        String respostaServidor = enviarRequisicaoUDP("CADASTRO;" + nome);
        
        if (respostaServidor != null) {
            String[] partes = respostaServidor.split(";");
            if (partes[0].equals("OK")) {
                String emailRecebido = partes[1];
                
                JOptionPane.showMessageDialog(this, "Cadastro realizado!\nSeu email institucional é:\n" + emailRecebido);
                
                txtEmailToken.setText(emailRecebido); 
                txtNome.setText(""); 
                
            } else {
                JOptionPane.showMessageDialog(this, partes[1], "Erro no Cadastro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro de rede (Timeout). Servidor não respondeu.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnPedirToken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblResultadoToken;
    private javax.swing.JTextField txtEmailToken;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
